[project]
name = "cantools"
readme = "README.md"
license = { file = "LICENSE" }
version = "1"
classifiers = ["Programming Language :: Python :: 3 :: Only"]
requires-python = ">=3.13,<3.15"

dependencies = [
    "bitstruct>=8.16.1",
    "python-can>=4.6.0",
    "textparser>=0.26",
    "argparse_addons",
    "crccheck",
    "diskcache"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
cache = ["diskcache"]
dev = [
    "matplotlib-stubs",
    "mypy",
    "pipx",
    "ruff",
    "tox",
]
plot = ["matplotlib"]
windows-all = [
    "windows-curses;platform_system=='Windows' and platform_python_implementation=='CPython'"
]

[tool.mypy]
show_error_codes = true
warn_return_any = true
warn_unused_configs = true
no_implicit_optional = true
disallow_incomplete_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
exclude = "^(?!cantools).*$"

[[tool.mypy.overrides]]
module = [
    "argparse_addons",
    "diskcache",
    "textparser",
    "bitstruct",
    "bitstruct.c",
    "matplotlib",
]
ignore_missing_imports = true
